// Generated by CoffeeScript 1.12.7
(function() {
  var ALL_SITES, DEFAULT_SITES, cooldown, filter, filter_all, listen, listener, msgListener, reload, storage, tabReplacedListener, unlisten, urlRegex;

  DEFAULT_SITES = [
    {
      hostSuffix: "notion.so"
    }
  ];

  ALL_SITES = [
    {
      urlMatches: ".*"
    }
  ];

  storage = chrome.storage.sync;

  filter = {
    url: DEFAULT_SITES
  };

  filter_all = {
    url: ALL_SITES
  };

  cooldown = 5;

  urlRegex = /^(([^:\/?#]+):)?(\/\/([^\/:?#]*))?([^?#]*)(\?([^#]*))?(#(.*))?/;

  listener = function(ev) {
    var i, len, ref, site;
    console.log("listener", ev);
    if (ev.frameId > 0) {
      return;
    }
    if (!ev.url.includes("http")) {
      return;
    }
    console.log("check", filter.url);
    ref = filter.url;
    for (i = 0, len = ref.length; i < len; i++) {
      site = ref[i];
      if (ev.url.includes(site.hostSuffix)) {
        console.log("whitelisted", ev);
        return;
      }
    }
    return chrome.tabs.executeScript(ev.tabId, {
      file: "content.js",
      runAt: "document_start",
      matchAboutBlank: true
    });
  };

  tabReplacedListener = function(ev) {
    return chrome.tabs.get(ev.tabId, function(tab) {
      var domain, ref;
      domain = (ref = urlRegex.exec(tab.url)) != null ? ref[4] : void 0;
      console.log(domain);
      if (!domain) {
        return;
      }
      return listener(ev);
    });
  };

  listen = function() {
    chrome.alarms.clearAll();
    chrome.webNavigation.onCommitted.addListener(listener, filter_all);
    chrome.webNavigation.onTabReplaced.addListener(tabReplacedListener);
    return chrome.runtime.onMessage.addListener(msgListener);
  };

  unlisten = function() {
    chrome.webNavigation.onCommitted.removeListener(listener);
    chrome.webNavigation.onTabReplaced.removeListener(tabReplacedListener);
    return chrome.runtime.onMessage.removeListener(msgListener);
  };

  msgListener = function(msg) {
    if (msg !== "clicked") {
      return;
    }
    unlisten();
    return listen();
  };

  reload = function() {
    return storage.get(['sites', 'cooldown'], function(result) {
      if (!result) {
        return;
      }
      if (Array.isArray(result.sites)) {
        filter = {
          url: result.sites
        };
      }
      if (result.cooldown) {
        cooldown = result.cooldown;
      }
      console.log("reload", filter, cooldown);
      unlisten();
      return listen();
    });
  };

  storage.get(['sites', 'cooldown'], function(result) {
    if (!result) {
      return;
    }
    if (Array.isArray(result.sites)) {
      filter = {
        url: result.sites
      };
    } else {
      storage.set({
        sites: DEFAULT_SITES
      });
    }
    if (result.cooldown) {
      cooldown = result.cooldown;
    } else {
      storage.set({
        cooldown: 5
      });
    }
    return chrome.alarms.get(function(alarm) {
      if (!alarm) {
        return listen();
      }
    });
  });

  chrome.alarms.onAlarm.addListener(listen);

  chrome.storage.onChanged.addListener(reload);

}).call(this);
